#Source: https://github.com/DaanVanYperen/libgdx-artemis-quickstart/blob/master/.travis.yml
#YAML OK with: http://lint.travis-ci.org/ (see: http://docs.travis-ci.com/user/travis-lint/)
#YAML OK with: http://www.yamllint.com/
language: android
android:
  components:
    - build-tools-20.0.0

before_install:
  - chmod +x gradlew

script: ./gradlew clean build

#Source: http://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: $GH_API_KEY
  file: |-
        - "android-debug.apk"
        - "android-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
#Source: http://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts: true
  s3_region: "us-west-1" # defaults to "us-east-1"
#Source: http://docs.travis-ci.com/user/uploading-artifacts/
#Adapted to libgdx
addons:
  artifacts:
    # relative path to APK, WAR, (TBD: IPA)
    paths:
    - $(ls /android/build/outputs/apk/*.apk | tr "\n" ":")
    - $(ls /html/build/libs/*.war | tr "\n" ":")
#    - $(git ls-files -o | tr "\n" ":")
#    - $(ls /var/log/*.log | tr "\n" ":")    
#    - $HOME/some/other/thing.log