#Source: https://github.com/DaanVanYperen/libgdx-artemis-quickstart/blob/master/.travis.yml
#YAML OK with: http://lint.travis-ci.org/ (see: http://docs.travis-ci.com/user/travis-lint/)
#YAML OK with: http://www.yamllint.com/
language: android
android:
  components:
    - build-tools-20.0.0

before_install:
  - chmod +x gradlew

script: ./gradlew clean build

#Source: http://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: $GH_API_KEY
  file: |-
        - "android-debug.apk"
        - "android-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
    