#Source: https://github.com/DaanVanYperen/libgdx-artemis-quickstart/blob/master/.travis.yml
language: android
android:
  components:
    - build-tools-20.0.0

before_install:
  - chmod +x gradlew

script: ./gradlew clean build

#get in contact with @rultor